/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LocaleChar125RouteImport } from './routes/{-$locale}'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as LoginRouteImport } from './routes/login'
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as Char123LocaleChar125AboutRouteImport } from './routes/{-$locale}/about'
import { Route as Char123LocaleChar125SlugRouteImport } from './routes/{-$locale}/$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AdminPreviewSlugRouteImport } from './routes/admin/preview.$slug'

const Char123LocaleChar125Route = Char123LocaleChar125RouteImport.update({
  id: '/{-$locale}',
  path: '/{-$locale}',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125AboutRoute =
  Char123LocaleChar125AboutRouteImport.update({
    id: '/about',
    path: '/about',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125SlugRoute =
  Char123LocaleChar125SlugRouteImport.update({
    id: '/$slug',
    path: '/$slug',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPreviewSlugRoute = AdminPreviewSlugRouteImport.update({
  id: '/admin/preview/$slug',
  path: '/admin/preview/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/{-$locale}': typeof Char123LocaleChar125RouteWithChildren
  '/{-$locale}/$slug': typeof Char123LocaleChar125SlugRoute
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/admin/': typeof AdminIndexRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/admin/preview/$slug': typeof AdminPreviewSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/{-$locale}/$slug': typeof Char123LocaleChar125SlugRoute
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/admin': typeof AdminIndexRoute
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
  '/admin/preview/$slug': typeof AdminPreviewSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/login': typeof LoginRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/{-$locale}': typeof Char123LocaleChar125RouteWithChildren
  '/{-$locale}/$slug': typeof Char123LocaleChar125SlugRoute
  '/{-$locale}/about': typeof Char123LocaleChar125AboutRoute
  '/admin/': typeof AdminIndexRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/admin/preview/$slug': typeof AdminPreviewSlugRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/robots.txt'
    | '/{-$locale}'
    | '/{-$locale}/$slug'
    | '/{-$locale}/about'
    | '/admin/'
    | '/{-$locale}/'
    | '/admin/preview/$slug'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/robots.txt'
    | '/{-$locale}/$slug'
    | '/{-$locale}/about'
    | '/admin'
    | '/{-$locale}'
    | '/admin/preview/$slug'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/login'
    | '/robots.txt'
    | '/{-$locale}'
    | '/{-$locale}/$slug'
    | '/{-$locale}/about'
    | '/admin/'
    | '/{-$locale}/'
    | '/admin/preview/$slug'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LoginRoute: typeof LoginRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  Char123LocaleChar125Route: typeof Char123LocaleChar125RouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AdminPreviewSlugRoute: typeof AdminPreviewSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/about': {
      id: '/{-$locale}/about'
      path: '/about'
      fullPath: '/{-$locale}/about'
      preLoaderRoute: typeof Char123LocaleChar125AboutRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/$slug': {
      id: '/{-$locale}/$slug'
      path: '/$slug'
      fullPath: '/{-$locale}/$slug'
      preLoaderRoute: typeof Char123LocaleChar125SlugRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/preview/$slug': {
      id: '/admin/preview/$slug'
      path: '/admin/preview/$slug'
      fullPath: '/admin/preview/$slug'
      preLoaderRoute: typeof AdminPreviewSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface Char123LocaleChar125RouteChildren {
  Char123LocaleChar125SlugRoute: typeof Char123LocaleChar125SlugRoute
  Char123LocaleChar125AboutRoute: typeof Char123LocaleChar125AboutRoute
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute
}

const Char123LocaleChar125RouteChildren: Char123LocaleChar125RouteChildren = {
  Char123LocaleChar125SlugRoute: Char123LocaleChar125SlugRoute,
  Char123LocaleChar125AboutRoute: Char123LocaleChar125AboutRoute,
  Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
}

const Char123LocaleChar125RouteWithChildren =
  Char123LocaleChar125Route._addFileChildren(Char123LocaleChar125RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LoginRoute: LoginRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  Char123LocaleChar125Route: Char123LocaleChar125RouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AdminPreviewSlugRoute: AdminPreviewSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
